# Generated by Django 5.2 on 2025-04-27 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passportNumber', models.CharField(max_length=10)),
                ('fullName', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=50)),
                ('jobTitle', models.CharField(max_length=50)),
                ('jobCategory', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('applicationStatus', models.CharField(choices=[('In-Progress', 'inprogress'), ('Approved', 'approved'), ('Rejected', 'rejected')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=1000)),
                ('rating', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=1)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VAMS_application.applications')),
            ],
        ),
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('employee', 'employee'), ('employer', 'employer'), ('admin', 'admin')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('organization', models.CharField(blank=True, default='No Information Available', max_length=1000)),
                ('educationalBackground', models.CharField(blank=True, default='No Information Available', max_length=100)),
                ('userProfileImage', models.FileField(upload_to='uploads/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='submittedBy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VAMS_application.userdatabase'),
        ),
    ]
