# Generated by Django 5.2 on 2025-04-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VAMS_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='submittedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VAMS_application.userdatabase'),
        ),
    ]
